### PR TITLE
New features: cd .. and find. Bug fix on decription.

### PR DESCRIPTION
**Pull request by arjunadeltoso**
Adding `cd ..` to the cd functionality. As expected it brings you to the parent directory.
Also fixed a bug in `path`: it was duplicating the current directory (in a structure like `/A/B/C`, `pwd` would print `//A/A/B/B/C/C`).

https://github.com/pypingou/revelationcli/pull/1/commits/5a25824dbc61407d7dac5ce06a22871384fad2e8 also fixes an error that prevented items with a description from being viewed.

### CODE REVIEW

**Comment by pypingou** [comment]
That is one piece of code I haven't touched in a long while ^^

Thanks for the patch! It looks good but I would like to test it before merging if that's ok with you (and I'll need a little time to do that)

**Comment by arjunadeltoso** [comment]
no problem, take your time =)

**Comment by arjunadeltoso** [comment]
@pypingou I find myself using pretty often revelationcli these days and I have a lot of passwords in my revelation file so to make finding the right one easier I've added a find feature. Hope you don't mind.

**Comment by pypingou** [comment]
tbh I have moved to https://www.passwordstore.org/ a while back and I'm no longer using revelation.

Would you like commit access to this project?

**Comment by arjunadeltoso** [comment]
> Would you like commit access to this project?

@pypingou if you wish, I've no problem merging the new code myself, I've been using it so should be pretty safe but please do have a look at it since I'm not a python developer.

**Comment by pypingou** [comment]
It looks all good to me from a brief look :)

I'll give you commit access to the repo, feel free to merge and ping me if you need/want more reviews :)

**Pull request merged**
